services:
  mysql:
    image: mysql:latest
    container_name: cc-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cc-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: